name: CD-reusable
on:
  workflow_call:
    inputs:
      cdTarget:
        required: true
        type: string
      buildFolder:
        required: true
        type: string
      domain:
        required: true
        type: string
      secretSuffix:
        required: false
        type: string
        default: ""
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      S3_BUCKET_REGION:
        required: true
      SLACK_WEBHOOK:
        required: true

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v3

      - name: Get Latest Tag
        id: latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1

      - name: Set Env
        if: always()
        run: |
          echo git describe
