name: CD-reusable
on:
  workflow_call:
    inputs:
      cdTarget:
        required: true
        type: string
      buildFolder:
        required: true
        type: string
      domain:
        required: true
        type: string
      secretSuffix:
        required: false
        type: string
        default: ""

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v3

      # - name: Get Latest Tag
      #   id: latest-tag
      #   uses: actions-ecosystem/action-get-latest-tag@v1

      - name: Set Env
        if: always()
        run: |
          git fetch --all --tags
          git tag -l --sort -v:refname > tagD
          echo "tag=$(echo `cat tagD`)" >> $GITHUB_ENV
      - name: Push tags
        run: |
          echo ${{ env.tag }}
