name: CD-reusable
on:
  workflow_call:
    inputs:
      cdTarget:
        required: true
        type: string
      buildFolder:
        required: true
        type: string
      domain:
        required: true
        type: string
      secretSuffix:
        required: false
        type: string
        default: ""

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v3

      # - name: Get Latest Tag
      #   id: latest-tag
      #   uses: actions-ecosystem/action-get-latest-tag@v1

      - name: Get the latest tag
        run: |
          git fetch --prune --unshallow
          git describe --tags > tag
          echo `cat tag` | cut -d '.' -f3 > patch
          echo "MAJOR=$(echo `cat tag`)" >> $GITHUB_ENV

      # 위의 환경변수를 활용하여 tag를 생성하고 push
      - name: Push tags
        run: |
          echo ${{ env.MAJOR }}
