name: CICD

on:
  push:
    branches:
      - main
      - qa

jobs:
  integration:
    uses: ./.github/workflows/ci_reusable.yml
    secrets: inherit

  deploy_info:
    name: get deploy info
    environment: production
    runs-on: ubuntu-latest

    outputs:
      rap_domain: ${{ steps.get-deploy-info.outputs.rap_domain }}
      secretSuffix: ${{ steps.get-deploy-info.outputs.secretSuffix }}

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v3

      - name: Get Deploy Info
        id: get-deploy-info
        run: |
          if [[ ${GITHUB_REF#refs/heads/} == "main" ]]
          then
          _rap_domain="${{ vars.MAIN_URL }}"
          _secretSuffix='MAIN'
          elif [[ ${GITHUB_REF#refs/heads/} == "qa" ]]
          then 
          _rap_domain="${{ vars.QA_URL }}"
          _secretSuffix='QA'
          echo "rap_domain=${_rap_domain,,}" >> $GITHUB_OUTPUT
          echo "secretSuffix=${_secretSuffix,,}" >> $GITHUB_OUTPUT

  deploy:
    needs: [integration, deploy_info]
    uses: ./.github/workflows/cd_reusable.yml
    with:
      domain: ${{ needs.deploy_info.outputs.rap_domain }}
      secretSuffix: ${{ needs.deploy_info.outputs.secretSuffix }}
      cdTarget: rap
      buildFolder: branch
    secrets: inherit
