# 개정노트(노션)에 개정 이력을 추가한다

name: Notion Versioning

on:
  push:
    branches:
      - develop
    tags:
      - "**"

  workflow_run:
    workflows: ["tagging"]
    types:
      - completed

jobs:
  notion-versioning:
    if: >
      (
        github.event_name == 'workflow_run' &&
        github.event.workflow_run.conclusion == 'success'
      )
      ||
      (
        github.event_name == 'push' &&
        startsWith(github.ref, 'refs/tags/v')
      )
    name: Notion versioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
