name: PR-Helper

on:
  pull_request:
    types:
      - labeled

jobs:
  pr-created:
    if: github.event.label.name == 'action:cd'
    name: pr-helper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Deploy Info
        id: get-deploy-info
        uses: ./.github/actions/deploy_info
